### ISSUE TITLE
Integration of information on survey areas

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/uc2-agriculture-biodiversity-nexus#2]
For NL, there is a dataset on where biodiv surveys have been performed. How can we utilize this additional information to better handle presence/absence of species?

**Comment by robknapen** [comment]
There is monitoring of this (for NDFF), but no published dataset that I know of. So I think at first we have to depend on the NDFF expert to provide this as quality/reliability information about their datasets. Should we be able to acquire such data, we can consider using it as an input for ML to estimate uncertainty of predictions. But this might be beyond the scope of the project.
