### ISSUE TITLE
Protection ratings on NL species

### ISSUE THREAD

**Issue by KathiSchleidt** [FAIRiCUBE/uc2-agriculture-biodiversity-nexus#3]
Within the NL species occurrence dataset, there are 3 levels of species:
- normal
- protected
- highly protected (only seen in nature preserves)

How can we utilize this information

**Comment by robknapen** [comment]
If we can classify species in such categories, in the machine learning / data analysis the more rare species can be considered more valuable. E.g. a highly protected species outside a known nature preserve can be a stronger signal of biodiversity increase (or a of a more favourable increase) than a higher abundance of 'normal' species.

However this might be complex to express in numbers and should  be done by domain experts. We can get back to it if there is sufficient time left in the project.
