### ISSUE TITLE
more models

### ISSUE THREAD

**Issue by pebau** [FAIRiCUBE/uc2-agriculture-biodiversity-nexus#6]
With rasdaman we are eager to support ML models more systematically, after the first breakthrough experiment. To this end, we'd need 
- more models, for establishing and evaluating a common model management schema
- for each model a description of its applicability (spatial, temporal, and any further relevant criteria)

Therefore, can you please provide us with say 5 - 10 different models plus description?

**Comment by robknapen** [comment]
Sure, we will make the ML models available as we develop them for the use case, based on the available data cubes. We hope to get back to such development activities after completing the review and our upcoming use case seminar (mid April).

Happy to discuss further after we get some UC model training going.

**Comment by pebau** [comment]
closing here, as I indeed have created the duplicate above:
https://github.com/FAIRiCUBE/FAIRiCUBE-Hub-issue-tracker/issues/57
